version: '3'
services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    container_name: api.go-task
    ports: 
      - "8080:8080"
    environment:
      DB_USERNAME: "go-task-user"
      DB_PASSWORD: "go-task-pass"
      DB_HOST: "{IP_MYSQL}"
      DB_PORT: "3306"
      DB_NAME: "go-task"
      GIN_MODE: release
      KAFKA_BROKERS: "{IP_KAFKA}:29092"

  worker:
    build:
      context: .
      dockerfile: worker.dockerfile
    container_name: worker.go-task
    environment:
      GIN_MODE: release
      KAFKA_BROKERS: "{IP_KAFKA}:29092"
